import { DatabaseSync } from 'node:sqlite';
import { closeSync, mkdirSync, openSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export const snapshotPath = fileURLToPath(new URL('../src-tauri/migrations/schema_snapshot.sql', import.meta.url));

export function buildSchema() {
    const source = readFileSync(new URL('../src-tauri/src/storage/database.rs', import.meta.url), 'utf8');
    const version = Number(source.match(/const LATEST_VERSION: i64 = (\d+);/)?.[1]);
    const migrations = [...source.matchAll(/const MIGRATION_(\d+): &str = include_str!\("([^"\n]+)"\);/g)]
        .map(match => ({ version: Number(match[1]), path: match[2] })).sort((a, b) => a.version - b.version);
    if (!version || migrations.length !== version || migrations.some((item, index) => item.version !== index + 1)) {
        throw new Error('Unrecognized Rust migration registry. Update this tool before generating a snapshot.');
    }
    const db = new DatabaseSync(':memory:');
    try {
        db.exec('PRAGMA foreign_keys=ON; BEGIN IMMEDIATE;');
        for (const migration of migrations) {
            db.exec(readFileSync(new URL(`../src-tauri/src/storage/${migration.path}`, import.meta.url), 'utf8').replace(/\r\n/g, '\n'));
        }
        db.exec(`PRAGMA user_version=${version}; COMMIT;`);
        const objects = db.prepare("SELECT type,name,sql FROM sqlite_schema WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'index' THEN 1 WHEN 'view' THEN 2 ELSE 3 END, rowid").all();
        const sql = [
            '-- GENERATED by npm run schema:sync. Do not edit manually.',
            '-- Full schema snapshot for NEW EMPTY databases only; not an incremental migration.',
            `-- Based on the registered Rust migrations through version ${version}. No application data.`,
            '-- Do not add this file to the runtime migration registry or execute all *.sql files.',
            'PRAGMA foreign_keys = ON;', 'BEGIN IMMEDIATE;',
            ...objects.map(object => `${object.sql};`),
            `PRAGMA user_version = ${version};`, 'COMMIT;', '',
        ].join('\n\n');
        return { sql, version, objects };
    } finally { db.close(); }
}

export function createEmptyDatabase(path, sql) {
    const target = resolve(path);
    mkdirSync(dirname(target), { recursive: true });
    // Exclusive creation refuses even an existing empty file; never overwrite
    // a developer's database or attempt to synchronize away their data.
    closeSync(openSync(target, 'wx'));
    let db;
    try {
        db = new DatabaseSync(target);
        db.exec(sql);
        if (db.prepare('PRAGMA foreign_key_check').all().length || db.prepare('PRAGMA quick_check').get().quick_check !== 'ok') {
            throw new Error('Generated database failed integrity checks.');
        }
    } catch (error) {
        db?.close();
        db = undefined;
        unlinkSync(target);
        throw error;
    } finally { db?.close(); }
    return target;
}

function main(args) {
    if (args.length && !(args.length === 1 && args[0] === '--check') && !(args.length === 2 && args[0] === '--create')) {
        throw new Error('Usage: node scripts/sync-schema.mjs [--check | --create <new-database-path>]');
    }
    const { sql, version, objects } = buildSchema();
    if (args[0] === '--check') {
        if (readFileSync(snapshotPath, 'utf8').replace(/\r\n/g, '\n') !== sql) throw new Error('Schema snapshot is stale. Run npm run schema:sync.');
        console.log(`Schema snapshot matches database version ${version} (${objects.length} objects).`);
    } else {
        if (args[0] === '--create') console.log(`Created empty database: ${createEmptyDatabase(args[1], sql)}`);
        writeFileSync(snapshotPath, sql);
        console.log(`Updated schema snapshot: ${snapshotPath} (database version ${version}).`);
    }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
    try { main(process.argv.slice(2)); }
    catch (error) { console.error(error.message); process.exitCode = 1; }
}
