-- GENERATED by npm run schema:sync. Do not edit manually.

-- Full schema snapshot for NEW EMPTY databases only; not an incremental migration.

-- Based on the registered Rust migrations through version 4. No application data.

-- Do not add this file to the runtime migration registry or execute all *.sql files.

PRAGMA foreign_keys = ON;

BEGIN IMMEDIATE;

CREATE TABLE books (
    id TEXT PRIMARY KEY NOT NULL,
    title TEXT NOT NULL CHECK (length(trim(title)) > 0),
    author TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'serializing' CHECK (status IN ('serializing', 'completed')),
    position INTEGER NOT NULL CHECK (position >= 0),
    is_read_only INTEGER NOT NULL DEFAULT 0 CHECK (is_read_only IN (0, 1)),
    database_version INTEGER NOT NULL DEFAULT 1 CHECK (database_version >= 1),
    created_at INTEGER NOT NULL CHECK (created_at >= 0),
    updated_at INTEGER NOT NULL CHECK (updated_at >= created_at)
, cover_color TEXT NOT NULL DEFAULT '') STRICT;

CREATE TABLE volumes (
    id TEXT PRIMARY KEY NOT NULL,
    book_id TEXT NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    title TEXT NOT NULL CHECK (length(trim(title)) > 0),
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
    position INTEGER NOT NULL CHECK (position >= 0),
    is_read_only INTEGER NOT NULL DEFAULT 0 CHECK (is_read_only IN (0, 1)),
    database_version INTEGER NOT NULL DEFAULT 1 CHECK (database_version >= 1),
    created_at INTEGER NOT NULL CHECK (created_at >= 0),
    updated_at INTEGER NOT NULL CHECK (updated_at >= created_at),
    UNIQUE (book_id, id)
) STRICT;

CREATE TABLE chapters (
    id TEXT PRIMARY KEY NOT NULL,
    book_id TEXT NOT NULL,
    volume_id TEXT NOT NULL,
    title TEXT NOT NULL CHECK (length(trim(title)) > 0),
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
    position INTEGER NOT NULL CHECK (position >= 0),
    content_format TEXT NOT NULL CHECK (content_format IN ('tiptap-json', 'legacy-json', 'legacy-html', 'unrecognized')),
    content_version INTEGER NOT NULL CHECK (
        (content_format = 'tiptap-json' AND content_version = 1) OR
        (content_format != 'tiptap-json' AND content_version = 0)
    ),
    content TEXT NOT NULL,
    -- Exact source retained before any legacy conversion. Never editor output.
    original_content TEXT,
    original_format TEXT CHECK (original_format IN ('legacy-json', 'legacy-html', 'unrecognized')),
    word_count INTEGER NOT NULL DEFAULT 0 CHECK (word_count >= 0),
    -- Keep complete notes, including unknown keys and historical non-UUID IDs.
    foreshadowings_json TEXT NOT NULL DEFAULT '[]' CHECK (
        CASE WHEN json_valid(foreshadowings_json) THEN json_type(foreshadowings_json) = 'array' ELSE 0 END
    ),
    is_read_only INTEGER NOT NULL DEFAULT 0 CHECK (is_read_only IN (0, 1)),
    database_version INTEGER NOT NULL DEFAULT 1 CHECK (database_version >= 1),
    created_at INTEGER NOT NULL CHECK (created_at >= 0),
    updated_at INTEGER NOT NULL CHECK (updated_at >= created_at),
    FOREIGN KEY (book_id, volume_id) REFERENCES volumes(book_id, id) ON DELETE CASCADE,
    CHECK ((original_content IS NULL) = (original_format IS NULL)),
    CHECK (content_format = 'tiptap-json' OR original_content IS NOT NULL),
    CHECK (content_format != 'tiptap-json' OR CASE WHEN json_valid(content)
        THEN json_type(content) = 'object' AND json_extract(content, '$.type') IS 'doc'
        ELSE 0 END)
) STRICT;

CREATE TABLE characters (
    id TEXT PRIMARY KEY NOT NULL,
    book_id TEXT NOT NULL,
    name TEXT NOT NULL CHECK (length(trim(name)) > 0),
    aliases_json TEXT NOT NULL DEFAULT '[]' CHECK (
        CASE WHEN json_valid(aliases_json) THEN json_type(aliases_json) = 'array' ELSE 0 END
    ),
    role TEXT NOT NULL DEFAULT 'supporting' CHECK (role IN ('protagonist', 'antagonist', 'supporting', 'mob')),
    description TEXT NOT NULL DEFAULT '',
    color TEXT NOT NULL DEFAULT '',
    tags_json TEXT NOT NULL DEFAULT '[]' CHECK (
        CASE WHEN json_valid(tags_json) THEN json_type(tags_json) = 'array' ELSE 0 END
    ),
    -- Optional: built-in avatar presets or colors only. Machine-local paths
    -- are not a migration promise and are never required.
    avatar TEXT,
    -- The character-level default handle configuration. A graph node either
    -- overrides it (its own non-null value) or follows this one — never both.
    handle_config_json TEXT CHECK (handle_config_json IS NULL OR json_valid(handle_config_json)),
    -- Deletion is archival: mentions, text and graph references stay.
    is_archived INTEGER NOT NULL DEFAULT 0 CHECK (is_archived IN (0, 1)),
    position INTEGER NOT NULL CHECK (position >= 0),
    database_version INTEGER NOT NULL DEFAULT 1 CHECK (database_version >= 1),
    created_at INTEGER NOT NULL CHECK (created_at >= 0),
    updated_at INTEGER NOT NULL CHECK (updated_at >= created_at),
    UNIQUE (book_id, id),
    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
) STRICT;

CREATE TABLE graphs (
    book_id TEXT PRIMARY KEY NOT NULL,
    database_version INTEGER NOT NULL DEFAULT 1 CHECK (database_version >= 1),
    created_at INTEGER NOT NULL CHECK (created_at >= 0),
    updated_at INTEGER NOT NULL CHECK (updated_at >= created_at),
    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
) STRICT;

CREATE TABLE graph_nodes (
    node_key TEXT PRIMARY KEY NOT NULL,
    book_id TEXT NOT NULL,
    character_id TEXT NOT NULL,
    position_x REAL NOT NULL CHECK (position_x BETWEEN -1000000 AND 1000000),
    position_y REAL NOT NULL CHECK (position_y BETWEEN -1000000 AND 1000000),
    -- NULL means "follow the character default"; non-null is a node override.
    handle_config_json TEXT CHECK (handle_config_json IS NULL OR json_valid(handle_config_json)),
    created_at INTEGER NOT NULL CHECK (created_at >= 0),
    updated_at INTEGER NOT NULL CHECK (updated_at >= created_at),
    UNIQUE (book_id, node_key),
    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE,
    FOREIGN KEY (book_id, character_id) REFERENCES characters(book_id, id) ON DELETE CASCADE
) STRICT;

CREATE TABLE graph_edges (
    id TEXT PRIMARY KEY NOT NULL,
    book_id TEXT NOT NULL,
    source_node_key TEXT NOT NULL,
    target_node_key TEXT NOT NULL,
    source_handle TEXT,
    target_handle TEXT,
    label TEXT NOT NULL DEFAULT '',
    created_at INTEGER NOT NULL CHECK (created_at >= 0),
    updated_at INTEGER NOT NULL CHECK (updated_at >= created_at),
    FOREIGN KEY (book_id, source_node_key) REFERENCES graph_nodes(book_id, node_key) ON DELETE CASCADE,
    FOREIGN KEY (book_id, target_node_key) REFERENCES graph_nodes(book_id, node_key) ON DELETE CASCADE
) STRICT;

CREATE TABLE planning (
    book_id TEXT PRIMARY KEY NOT NULL,
    story_summary TEXT NOT NULL DEFAULT '',
    story_background TEXT NOT NULL DEFAULT '',
    chapter_summaries_json TEXT NOT NULL DEFAULT '[]' CHECK (
        CASE WHEN json_valid(chapter_summaries_json) THEN json_type(chapter_summaries_json) = 'array' ELSE 0 END
    ),
    plot_settings_json TEXT NOT NULL DEFAULT '[]' CHECK (
        CASE WHEN json_valid(plot_settings_json) THEN json_type(plot_settings_json) = 'array' ELSE 0 END
    ),
    database_version INTEGER NOT NULL DEFAULT 1 CHECK (database_version >= 1),
    created_at INTEGER NOT NULL CHECK (created_at >= 0),
    updated_at INTEGER NOT NULL CHECK (updated_at >= created_at),
    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
) STRICT;

CREATE TABLE application_preferences (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    dark_mode INTEGER CHECK (dark_mode IS NULL OR dark_mode IN (0, 1)),
    editor_margin_px INTEGER CHECK (editor_margin_px IS NULL OR editor_margin_px BETWEEN 24 AND 72),
    editor_line_height REAL CHECK (editor_line_height IS NULL OR editor_line_height BETWEEN 1.2 AND 1.8),
    ai_continue_context_chars INTEGER CHECK (ai_continue_context_chars IS NULL OR ai_continue_context_chars BETWEEN 500 AND 6000),
    ai_continue_output_chars INTEGER CHECK (ai_continue_output_chars IS NULL OR ai_continue_output_chars BETWEEN 120 AND 800),
    auto_highlight_json TEXT CHECK (auto_highlight_json IS NULL OR json_valid(auto_highlight_json)),
    database_version INTEGER NOT NULL DEFAULT 1 CHECK (database_version >= 1),
    created_at INTEGER NOT NULL CHECK (created_at >= 0),
    updated_at INTEGER NOT NULL CHECK (updated_at >= created_at)
) STRICT;

CREATE TABLE brainstorm_workspaces (
    book_id TEXT PRIMARY KEY NOT NULL,
    selected_chapter_ids_json TEXT NOT NULL DEFAULT '[]' CHECK (
        CASE WHEN json_valid(selected_chapter_ids_json) THEN json_type(selected_chapter_ids_json) = 'array' ELSE 0 END
    ),
    context_snapshot_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(context_snapshot_json)),
    generated_options_json TEXT NOT NULL DEFAULT '[]' CHECK (
        CASE WHEN json_valid(generated_options_json) THEN json_type(generated_options_json) = 'array' ELSE 0 END
    ),
    selected_option_id TEXT,
    final_content TEXT NOT NULL DEFAULT '',
    database_version INTEGER NOT NULL DEFAULT 1 CHECK (database_version >= 1),
    created_at INTEGER NOT NULL CHECK (created_at >= 0),
    updated_at INTEGER NOT NULL CHECK (updated_at >= created_at),
    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
) STRICT;

CREATE TABLE ai_model_configs (
    id TEXT PRIMARY KEY NOT NULL CHECK(length(id) = 36),
    name TEXT NOT NULL CHECK(length(trim(name)) BETWEEN 1 AND 120),
    protocol TEXT NOT NULL CHECK(protocol IN ('openai-responses','openai-chat-completions','anthropic-messages')),
    base_url TEXT NOT NULL CHECK(length(base_url) BETWEEN 1 AND 2048),
    model_id TEXT NOT NULL CHECK(length(trim(model_id)) BETWEEN 1 AND 256),
    timeout_ms INTEGER NOT NULL CHECK(timeout_ms BETWEEN 1000 AND 600000),
    max_output_tokens INTEGER NOT NULL CHECK(max_output_tokens BETWEEN 1 AND 1000000),
    credential_ref TEXT UNIQUE CHECK(credential_ref IS NULL OR length(credential_ref) = 36),
    config_version INTEGER NOT NULL DEFAULT 1 CHECK(config_version > 0),
    created_at INTEGER NOT NULL CHECK(created_at >= 0),
    updated_at INTEGER NOT NULL CHECK(updated_at >= created_at)
) STRICT;

CREATE TABLE ai_generation_settings (
    id INTEGER PRIMARY KEY CHECK(id = 1),
    default_config_id TEXT REFERENCES ai_model_configs(id) ON DELETE RESTRICT,
    database_version INTEGER NOT NULL DEFAULT 1 CHECK(database_version > 0),
    updated_at INTEGER NOT NULL CHECK(updated_at >= 0)
) STRICT;

CREATE INDEX books_order ON books(position, id);

CREATE INDEX volumes_order ON volumes(book_id, position, id);

CREATE INDEX chapters_order ON chapters(book_id, volume_id, position, id);

CREATE INDEX characters_book_order ON characters(book_id, position, id);

CREATE INDEX graph_nodes_book ON graph_nodes(book_id, node_key);

CREATE INDEX graph_edges_book ON graph_edges(book_id, id);

PRAGMA user_version = 4;

COMMIT;

